spring:
  sql:
    init:
      encoding: UTF-8

  h2:
    console:
      enabled: true

  jpa:
    # 쿼리 확인ㄴ
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 689056871882-1rd379amv9r0kp4ia4c7brb17b6m4h2m.apps.googleusercontent.com
            clientSecret: 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

jwt:
  issuer: kji0205@gmail.com
  secret_key: study-springboot
